// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pekbysqbrihyxmyxoruq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBla2J5c3FicmloeXhteXhvcnVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTk0MTQsImV4cCI6MjA2ODA5NTQxNH0.z5Q2zjmIuQWVn9wwCmN4G07y-WCWevOIT1nJlJxzGFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});